### ISSUE TITLE
Allow additional operator managed namespaces

### ISSUE THREAD

**Issue by bastjan** [projectsyn/component-prometheus#44]
## Context

The operator is set to manage namespaces created from the `namespaces: {}` object.
If a namespace already exists from other sources it is not possible to manage this namespace.

This would allow the operator to manage existing/additional Prometheuses from other sources like `component-rancher-monitoring`.

#### Proposed config:

```yaml
parameters:
  prometheus:
    prometheusOperator:
      additionalManagedNamespaces:
        - blub
```

The parameter would be merged with the namespaces from the `namespaces: {}` object.

## Alternatives

cc @TheBigLee
