### ISSUE TITLE
Custom Prometheus version is ignored

### ISSUE THREAD

**Issue by mhutter** [projectsyn/component-prometheus#99]
No matter the version configured, the Prometheus image will always be the same: `quay.io/prometheus/prometheus:v2.29.1`.

## Steps to Reproduce the Problem

Given this configuration

```yaml
parameters:
  prometheus:
    instances:
      some:
        prometheus:
          enabled: true
          config:
            version: v1.33.7
```

## Actual Behavior

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
# ...
spec:
  image: quay.io/prometheus/prometheus:v2.29.1
  version: v1.33.7
# ...
```

## Expected Behavior

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
# ...
spec:
  image: quay.io/prometheus/prometheus:v1.33.7
  version: v1.33.7
# ...
```

**Comment by mhutter** [comment]
Turned out to be PEBCAK. Instead:

```
parameters:
  prometheus:
    instances:
      some:
        common:
          versions:
            prometheus: 1.33.7
```

This is the way.
